### ISSUE TITLE
求修复

### ISSUE THREAD

**Issue by xideoo** [HSLix/LixAssistantLimbusCompany#1]
选镜牢2会选到镜牢1

**Comment by HSLix** [comment]
请上传日志文件，并说明时间，我好做错误判断分析

**Comment by xideoo** [comment]
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12683734/debugLog.log)

**Comment by HSLix** [comment]
我想确认一下，你的游戏语言是英语，且游戏窗口经过程序调整吧？以及你的操作系统是win10或者win11？

**Comment by xideoo** [comment]
都是按照要求设置好了，以及可以识别并且进去了，但是无论选择1还是2最终都会进入到1

**Comment by HSLix** [comment]
好的，我会进行调整修复，稍后下载2.1.3试一下吧

**Comment by xideoo** [comment]
感谢

**Comment by HSLix** [comment]
2.1.3已发布，可以下载来测试下

**Comment by HSLix** [comment]
没问题的话，反馈一下吧

**Comment by HSLix** [comment]
然后可以说一下你是怎么知道这个软件的吗

**Comment by xideoo** [comment]
在贴吧刷到的（ 
刚好二号线缺资源想试试

**Comment by HSLix** [comment]
原来是贴吧啊，是有谁帮我宣传吧

**Comment by xideoo** [comment]
![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/145665341/b2f63579-fe31-4db6-932a-09c03938f522)
进入之后就卡住了，不清楚什么原因

**Comment by HSLix** [comment]
可以重启再启动试试？

**Comment by HSLix** [comment]
是进到这个界面就出错吗？

**Comment by HSLix** [comment]
果然自己测试是很有限的，程序在别人的电脑跑才会暴露问题

**Comment by xideoo** [comment]
重启之后还是一样，主要就是选好人进了地牢之后不会自动选路，鼠标就一直卡在左上角，然后卡个十几秒就提示这个弹窗

**Comment by xideoo** [comment]
我个人建议其实ego技能不用释放都可以，只要纯p就行

**Comment by HSLix** [comment]
但我有做避免缩放影响的操作，真是奇怪

**Comment by xideoo** [comment]
我是2560×1440，125%

**Comment by HSLix** [comment]
我自己把分辨率调整了，不影响，不过缩放一调整就出现相同问题，确实是缩放率的问题

**Comment by HSLix** [comment]
在缩放调整为150%后，还有问题吗？急，在线等

**Comment by HSLix** [comment]
我稍后得把缩放率这条补充一下

**Comment by xideoo** [comment]
目前没有了，感谢大佬，还在测试，如果有什么问题第一时间告诉你

**Comment by HSLix** [comment]
ok，可以的话点颗星星吧，这是对我最大的鼓励！！

**Comment by xideoo** [comment]
还有一个问题我不清楚是不是程序bug，就是有些关卡打完之后会推出去吃一次体力，刚刚打第一层连续退了两次出去吃体力，我一开始还以为是固定每个时间段执行一次来着，如果频繁推出去有点浪费时间感觉

**Comment by HSLix** [comment]
这个不算bug，退出去是因为程序识别不出自己所在的地方，很可能是由于黑屏加载时间过长，在我自己的电脑上很少发生

**Comment by xideoo** [comment]
不是什么大问题，可能你电脑配置比较高加载比较快，我观察了一下，就是当车头不在屏幕中间位置的时候它就可能会退出去再进来，我电脑没下录制软件，如果之后有比较麻烦的情况我再录个视频给你，目前情况我感觉口述可以说清楚

**Comment by HSLix** [comment]
哦哦，是这样，我的寻路识图基础是车头在中央，或者其它关卡在中央，其余情况不太好做寻路，我计划后面会有备用寻路方式。如果有什么想法或建议都可以提出来

**Comment by HSLix** [comment]
如果没什么，我稍后就关闭这个Issue啦，祝你玩得开心~

**Comment by xideoo** [comment]
好的，辛苦了，如果有投喂可以贴出来，如果用一段时间没问题我会适当投喂=。=

**Comment by HSLix** [comment]
不用投喂，谢谢你的心意啦。
我做这个就是看不惯有些收费的脚本或者封闭自萌的脚本，免费、开源，最好能有大神加入开发继续发扬，这是我的目标。
可以的话，能在周围分享一下你使用这个软件的体验就好，我希望更多的人不用受到limbus中不太好的游玩过程折磨，只用享受它精彩的部分

**Comment by xideoo** [comment]
确实折磨，一堆四破+人格ego，如果没有脚本真刷不动这么箱子，毕竟平时还要上班学习，感谢付出

**Comment by haohaoguai** [comment]
大佬，那1920*1080分辨率是用不了了么

**Comment by xideoo** [comment]
和分辨率好像没关系，只要把那个缩放调一下应该就行了

**Comment by haohaoguai** [comment]
这个一拖到左上角分辨率就会自动调成1514*808，应该是这个问题，也不知道这个怎么解决

**Comment by HSLix** [comment]
可以的话，先将自己的屏幕分辨率调为2560×1440，或者与之相近的分辨率，缩放定为150%，这样的问题我先记下，后面尽快解决

**Comment by HSLix** [comment]
唉？！

**Comment by HSLix** [comment]
我做了个小补丁，自己电脑设为1920x1080，缩放150，可以用

**Comment by HSLix** [comment]
稍等，你下载2.1.4的版本吧

**Comment by HSLix** [comment]
> 那我还是等等吧，我这老笔记本只能搞1920了

马上上传，你来测试一下

**Comment by haohaoguai** [comment]
okok万分感谢

**Comment by HSLix** [comment]
ok，只要缩放为150%，且屏幕里有完整游戏窗口，都能识别

**Comment by HSLix** [comment]
稍等哈，梯子太烂了，release上传断断续续的

**Comment by HSLix** [comment]
> okok万分感谢

我也感谢你们的反馈与测试，你们也同样参与到这个软件的开发！
另外，2.1.4刚发好了，请下载测试一下，可以的话回来反馈一下

**Comment by HSLix** [comment]
> okok万分感谢

求反馈，急，在线等QAQ

**Comment by haohaoguai** [comment]
okok，这会能动了，万分感谢大佬

**Comment by haohaoguai** [comment]
已经点了lol，赞美大佬

**Comment by HSLix** [comment]
既然问题解决啦，这个issue就关了吧，方便后面解决其它的问题

**Comment by HSLix** [comment]
最后祝各位晚安好啦
