### ISSUE TITLE
因关卡未完全解锁，在 EXP 和 Thread 时出现没有选取最高难度和无法刷取的情况

### ISSUE THREAD

**Issue by changlaplace** [HSLix/LixAssistantLimbusCompany#106]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等 | The title is clear rather than "A advice".
- [X] 我已确认目前没有类似 issue | I have confirmed that there is no similar issue at this time.
- [X] 我确定这是一个建议，而不是遇到了问题 | I'm sure it was a suggestion, not a problem encountered
- [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 | I understand and am willing to follow up on this issue, assist with testing and provide feedback.
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 | I understand and agree with the above, and understand that project maintainers have limited energy, and that issues that don't follow the rules may be ignored or simply shut down

### 建议

1.Thread纽本进入luxeration的thread之后不停按退出键，不能开启battle，我的电脑是这样的，很奇怪
2.EXP每次刷的都是等级最低的那个，即diffculty为lv20的，造成资源浪费
3.mirror一开始的时候select ego gift有时候会卡住，我尝试在mirror4Cope的Skip后面加入
#################################
if self.single_target_click("./pic/event/Confirm.png", "Confirm", 0, 0, 0.8, 1):
self.cap_win()
if self.single_target_click("./pic/event/RefuseGift.png", "RefuseGift", 0, 0, 0.8, 1):
self.cap_win()
###############################来粗暴解决
4.Mirror的Choose themepack的时候卡住，貌似电脑无法识别新commit的复杂选取函数，我觉得还是换成原来的简单drag能稳定一点，但是我这个电脑需要自己修改一下drag的起始终止坐标，
在这里mirror4ChooseThemePack(self)改为：
self.Ori_click_locate_and_drag_to(600, 450, 600, 800, "FirstThemePack")，
顺便可以使用屏幕的相对坐标？
5.mirror有的battle一开始会触发warning闪烁，这时候allwinrate里面的press p就没有相应了，造成卡关。
def allWinRateBattle(self)这个函数里面需要用click来破掉warning：
为作者的辛勤付出点赞

**Comment by HSLix** [comment]
我先对你的问题一一回答好了
1. 没有日志和相关对应时间，我没法完全确认具体问题，但这个问题属于的昨日版本修复的内容才对；
2. 同样是昨日版本更新修复的内容，在陆爻齐本地运行正常捏
3. cope 补充 confirm 的情况挺好的，不过这个 Refuse GIft 没啥必要
4. 坐标会随游戏窗口变动，写相对坐标即可，2.1.12 及以前就用了一个万用的主题选择坐标，可参考；你自己试出来也可以
5. 这个也是昨日版本修复内容

既然会主动修改代码，那么我猜你是 clone 代码后，在本地运行是吗？嘛，建议还是优先用 release ，毕竟有时候代码确实忘记 push 上来，也不一定会 push 到 master，不过 release 一定是最新的（吧：）

**Comment by changlaplace** [comment]
<img width="586" alt="Screenshot 2024-08-26 124217" src="https://github.com/user-attachments/assets/d981012a-641e-44b2-933e-5f176a6af510">
感谢作者，我会持续关注。EXP还是只能打lv20的，是代码写的lv40但我还没解锁？但是我能打lv30的。Thread那个是来回在图里面的thread和enter之间点击，，，我再想想，我也不着急打thread，主要用mirron

**Comment by HSLix** [comment]
你给了图片我就知道问题所在了，你没有全部解锁这些关，因为 LALC 在立项时，陆爻齐早过新手期了，而且也默认用户也都是牢玩家，你的 Issue 还是很有意义的，后续我得补充点前提条件适配下才行

EXP 默认识别的是 43 等级的，毕竟牢玩家的界面图片如下，
![image](https://github.com/user-attachments/assets/628a2f79-c68d-4abb-ab1b-311539b5af40)

既然找不到特别正确，20 级又有点像，就出现这个“点错”的问题了

以及，thread的问题在这种情况下是正常的，你要是仔细点看这些屎山代码，就会发现识图核心就是直接的模板匹配，不过我让流程变成了，如果无法下一步，就退回一开始重来，所以就几乎死循环了

嘛，等你成为牢玩家，应该也能用啦：）那么问题解决，这个 Issue 就可以关咯
