### ISSUE TITLE
Stuck at the beginning of Mirror Dungeon Random Select E.G.O Gift

### ISSUE THREAD

**Issue by Endymiionn** [HSLix/LixAssistantLimbusCompany#107]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题 | I have google it and can hardly find any solution.
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等 | The title is clear rather than "A advice".
- [X] 我已确认目前没有类似 issue | I have confirmed that there is no similar issue at this time.
- [X] 我使用的程序版本已为最新版 | The programme is the latest version.
- [X] 我已完整查看过项目 README，尤其是常见问题部分 | I have reviewed the project README in its entirety, especially the FAQ section
- [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 | I understand and am willing to follow up on this issue, assist with testing and provide feedback.
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 | I understand and agree with the above, and understand that project maintainers have limited energy, and that issues that don't follow the rules may be ignored or simply shut down

### 问题描述

getting stuck at Select E.G.O Gift at start of Mirror Dungeon it runs fine when this is bypassed by clicking/running the dungeon first 

### 重现问题

Windows 11
1920x1080 150%  resolution.
Started the game in Windowed Mode
Start the program
It runs fine but it ends on the Random Select E.G.O Gift before the start of the mirror dungeon

### 日志文件

[2024-09-06.0001.debugLog.log](https://github.com/user-attachments/files/16907265/2024-09-06.0001.debugLog.log)
[2024-09-06.0001.infoLog.log](https://github.com/user-attachments/files/16907267/2024-09-06.0001.infoLog.log)
[2024-09-06.0001.warningLog.log](https://github.com/user-attachments/files/16907268/2024-09-06.0001.warningLog.log)

### 视频/截图

<img width="949" alt="image" src="https://github.com/user-attachments/assets/cc766b31-fb20-4fb6-9a7e-16fbba582b5a">

### 应该是？

Program should continue to run until the end of Mirror Dungeon run,

### 其他信息

Windows 11
Limbus Language : English
System Language : English
Screen Resolution : 1920x1080 150%
Limbus ver. 1.56.0
LixAssistant ver.V2.1.13_Debug.

**Comment by HSLix** [comment]
emmm，you would know how to deal with it if you check release when you update lalc
![image](https://github.com/user-attachments/assets/b4874f85-d5ce-4ece-ac0e-786c53be85b8)

**Comment by Endymiionn** [comment]
> emmm，you would know how to deal with it if you check release when you update lalc ![image](https://private-user-images.githubusercontent.com/112762490/365235584-b4874f85-d5ce-4ece-ac0e-786c53be85b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDQ2MzAsIm5iZiI6MTcyNTY0NDMzMCwicGF0aCI6Ii8xMTI3NjI0OTAvMzY1MjM1NTg0LWI0ODc0Zjg1LWQ1Y2UtNGVjZS1hYzBlLTc4NmM1M2JlODViOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNzM4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZTI0ZmRmODhiMTE0NzM4Yjc2YzZlNDkwM2QyNzgwZThiODgyY2YzNWRhODU0ZjMwZDE5YzY0OWY2ZTYxMzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.spC5BFr0o5Zu_JTQFp7g_c8HhJzluZhepIG790COV-k)

Apologies as I am quite new to the Mirror Dungeon 4, do I have to buy an upgrade to show Poise ?

**Comment by HSLix** [comment]
> Apologies as I am quite new to the Mirror Dungeon 4, do I have to buy an upgrade to show Poise ?

the update of poise is free, above of the center.

**Comment by Endymiionn** [comment]
was able to figure it out I had to use the starlight upgrades to get the poise, thank you

**Comment by Endymiionn** [comment]
was able to figure it out I had to use the starlight upgrades to get the poise, thank you
