### ISSUE TITLE
增加选人顺序的调整

### ISSUE THREAD

**Issue by yenanxiao** [HSLix/LixAssistantLimbusCompany#11]
1.增加镜牢2普通难度是否选择只打到第三层或全五层按键。（原因：前三层时间投入/收入 性价比最高）
2.增加选人界面选人顺序自定义按钮，例：1234567 的选人顺序可改为7324561（原因：如刷关优先选七号位罪人，但原脚本第一层只能选到1-5号位罪人，不利于阵容推关）

                                                                                                                                      更多建议会在以后实际测试后提出
                                                                                                                                                                 望作者采纳

**Comment by HSLix** [comment]
谢谢你的支持与提议，你的意见我已经记下，都会在后续更新中逐一实现
