### ISSUE TITLE
镜牢二走到非战斗格后无法直接走到下一格

### ISSUE THREAD

**Issue by Louisskenn** [HSLix/LixAssistantLimbusCompany#12]
首先真心感谢大佬製作这个程序，终于不用手动刷镜牢了。
不是中断的Bug,只是有点拖时间的BUG。
测几次后找到规律就来回报看看。

从第二层开始有机率会发生，
走了上层路线后踩到非战斗格，
离开后镜牢会放大显示倍率，导致无法侦测到下一格。
然后自动切回主画面后重进一次才会显示正常的倍率。

22:40
![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/146411651/48338d56-9fc2-4ceb-a2f4-cd60dc2a4d7a)
离开休息格后的样子
![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/146411651/6f9be022-6f66-4e5d-b04d-8c9d2021a76b)
下一格撞商店出来后

22:54 第三层,上线走到问号后终点刚好被盖住
![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/146411651/f61557c1-7afb-44e2-8484-7a78aa212797)

![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/146411651/d266adbf-2568-4106-8ba0-4c98ded14770)
手操后发现也有同样情况，这显示倍率超出最小值，
滑鼠滚轮往上滚也滚不到这麽小。一滚就回归下图的正常大小。

请问是否可以增加一个操作是离开格子后自动滚轮的操作？

附件：
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12777471/debugLog.log)

OS:win10
Screen 1920X1080(150%)
ReleaseVersion 2.17

**Comment by HSLix** [comment]
感谢你的支持与意见，我会尝试在新的版本中加入相关功能

**Comment by HSLix** [comment]
2.1.8已更新，功能已经加上啦

**Comment by HSLix** [comment]
不过，恢复原来视图后，由于火车不在中心，大概率还是无法做下一次的定位，识图点击还有很大进步空间啊

要是有新的idea或者建议，欢迎再提新的issue吧
