### ISSUE TITLE
程序打不开

### ISSUE THREAD

**Issue by TakeyourTea** [HSLix/LixAssistantLimbusCompany#15]
使用2.1.7版本，无法打开程序。
![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/146742999/9e358f81-5f39-47b2-8a4c-ef909da85c8c)
![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/146742999/85dcb6f7-4340-4e4c-a833-5bf4c64d962a)

**Comment by HSLix** [comment]
请按照以下步骤试着操作一下：
在Windows操作系统中：

打开控制面板(Control Panel)。
选择"时钟和区域"（Clock and Region）。
在"区域"（Region）部分，点击"更改日期、时间或区域格式"（Change date, time, or number formats）。
在弹出的窗口中，选择"管理"（Administrative）选项卡。
在"语言设置更改"（Language for non-Unicode programs）部分，点击"更改系统区域设置"（Change system locale）。
选择"使用Unicode UTF-8 提供全球语言支持"（Use Unicode UTF-8 for worldwide language support）。
点击"确定"（OK）按钮，并按照系统提示重新启动电脑。

**Comment by TakeyourTea** [comment]
已经解决开始快乐刷地牢

**Comment by HSLix** [comment]
感谢反馈，可以的话，点颗星星支持一下吧

**Comment by HSLix** [comment]
既然问题顺利解决了，那就也close了吧
