### ISSUE TITLE
无法正常使用

### ISSUE THREAD

**Issue by cldwinter** [HSLix/LixAssistantLimbusCompany#16]
之前可以正常使用 最近两天无法使用 点击开始后显示：当前页面无法回到初始主页面 ，无法继续任务。
分辨率 游戏窗口位置均确认无误

**Comment by cldwinter** [comment]
已删除零协汉化补丁 也尝试过重启等方式均无效果

**Comment by HSLix** [comment]
你的系统是win10或win11吗

以及最好把日志文件发出来，这样找bug效率高些

**Comment by cldwinter** [comment]
系统是win10 不太清楚哪个是日志文件以及上传方式

**Comment by HSLix** [comment]
但从你的描述看，我觉得这个bug有玄学因素

**Comment by cldwinter** [comment]
确实有玄学因素 今天就能用了 但是总是卡在战斗界面
一直重复点胜率那个自动连线 不点开始

**Comment by HSLix** [comment]
本以为是部分因素识图准确率要求过高，现在新问题又变成识图准确率要求可能过低。。。

总之我会稍微细调你的描述中难以识图相关元素。

可以的话，希望你能在游戏中尝试打开各种界面，然后启动程序返回主界面，看看哪些情况识图还有问题

**Comment by HSLix** [comment]
2.1.8已更新，可以反馈下问题解决了吗？
