### ISSUE TITLE
脚本运行次数错误，选人界面重复选择导致只有一两个人上场

### ISSUE THREAD

**Issue by GYLuuing** [HSLix/LixAssistantLimbusCompany#17]
目前遇到有两个问题：
1.在脚本界面我设置的是镜本5次，经验和纺锤各一次，领取邮件和日常
<img width="406" alt="image" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/147010597/be0155bf-69c4-4ccd-a871-4ea07c32e526">
脚本启动之后开始买体力，换绿饼，经验本，纺锤本，之后就是进入镜本，在第一次镜本的过程中切出去领了邮件，然后就是第一个问题，因为脚本检测不到下一个路径点，所以重新进入了镜本，进入战斗关卡后，需要重新选人，这时脚本会从1——12，再1——12这个顺序选人，这就导致了第一遍选上的人被取消了，因为上场人数限制没被选上的被选上了。具体情况可以看这个视频https://www.bilibili.com/video/BV19V411F7tH/?vd_source=e0a34381ccea702872836b5955b1c0de
2.我设置的是镜本5次，然而脚本连一次都没有打完就自动结束了，我估计可能跟上面的那个问题有关系，重新进入镜本可能被识别为完成了一次任务
以下是日志文件：
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12811218/debugLog.log)
[warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12811219/warningLog.log)
希望的改进：
1.增加一个是否购买体力的选项，不然每次重新打开软件就会购买一次体力
2.任务顺序改进一下，准备打纺锤了，结果跳到镜本的界面再跳回来，又或者是在打镜本的时候跳出去领邮件去了。
非常感谢大佬为我们提供的宝贵工具，希望我的反馈和建议能够对大佬有所帮助

**Comment by HSLix** [comment]
1、选人问题与逻辑无关，经排查，是识别图片模板有问题导致，所以在第二层可以4个人时才有问题，下次更新2.1.8即可修复
2、一次没有打完就结束不是因为进入镜本算一次完成，而是判定5次进入镜本中没有做任何有效操作，如完成一场战斗，实现一次事件等才退出，刚好五次
3、是否购买体力的选项正在实现
4、任务顺序方面，我没从日志上发现什么异常，领邮件只会在最后结算才会，打镜本中途退出刷新视角后只会转换体力（下个版本删），可以的话，希望也能提供视频，或带有具体开始时间和日志文件

**Comment by HSLix** [comment]
当然也谢谢你的反馈呀

**Comment by HSLix** [comment]
2.1.8已更新，可以反馈下问题解决了吗？

**Comment by GYLuuing** [comment]
问题已经解决了，我再多试几次看看有没有其他的情况。

**Comment by HSLix** [comment]
okay，再有什么问题就提新issue吧

**Comment by HSLix** [comment]
这个issue还是关了吧，太久啦
