### ISSUE TITLE
商店选择问题

### ISSUE THREAD

**Issue by Zttfwy** [HSLix/LixAssistantLimbusCompany#18]
我看进入商店时都是直接离开，如果考虑到ego会有负效果的问题的话，可以选择用1技能替换2技能。这样可以提高推图速度的同时又不会让W唐、W良之类的充能人格强度下降。

**Comment by HSLix** [comment]
感谢建议，但进入商店后比较好的，通用的方式暂时还没定论，等以后有类似投票之类的再仪吧
