### ISSUE TITLE
求解决

### ISSUE THREAD

**Issue by zolgen** [HSLix/LixAssistantLimbusCompany#2]
在刷镜牢1的时候，第一次进入关卡选择罪人时脚本会尝试点击左上角和战斗按钮，但是脚本不选择罪人无法进入战斗然后就这样一直循环，求大佬帮忙解决！分辨率是1920x1080，游戏分辨率是脚本启动后自动调整的，缩放也是150％，脚本使用起来没有异常，如果不自己在选罪人界面手动选择脚本就不会进行下去而是一直循环点击左上角和战斗按钮。

**Comment by zolgen** [comment]
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12707166/debugLog.log)

**Comment by zolgen** [comment]
![LB{LBS$MQJ4D7~K3C5Q09JK](https://github.com/HSLix/LixAssistantLimbusCompany/assets/110576054/d1910cf5-775e-4f7c-adbe-f9b0e1415972)

**Comment by zolgen** [comment]
win10，缩放率150

**Comment by HSLix** [comment]
感谢你的反馈与支持，问题原因已经找出并解决，我正在进行镜牢1全套测试，请下载稍后的2.1.5版本测试

**Comment by HSLix** [comment]
2.1.5版本已发布，可以下载测试啦，然后麻烦一下，反馈问题是否解决

**Comment by HSLix** [comment]
可以的话，点颗星星Star吧orz

**Comment by zolgen** [comment]
感谢大佬解决，星星已点，正在下载新版本测试

**Comment by zolgen** [comment]
大佬，目前镜一选罪人的问题解决了，但是 镜一不能连续刷，不管镜本底下的数字填多少，都只是刷一遍任务就结束了。

**Comment by zolgen** [comment]
镜本刷一遍之后会重新进一遍，然后在第一关那里退出去领任务，然后就结束了，不会再刷
