### ISSUE TITLE
脚本开启后对某几个点重复点击 不能正常工作

### ISSUE THREAD

**Issue by walkman205** [HSLix/LixAssistantLimbusCompany#20]
完成设置之后点击开始脚本，脚本重置画面位置和大小后点击重复某几个点，然后就一直循环重复
只重置画面位置也是一样的结果

详情看：https://youtu.be/qa0iQdWrMHk 

因为没有报错我就没有上传log文件，如有需要请作者告知，感谢分享

**Comment by HSLix** [comment]
首先先感谢提供了详实的视频记录
然后，日志文件还是需要提供的，毕竟查询细节都在里面

不过从视频我大概清楚情况了，很像以前受到缩放影响，识图成功，但点击坐标出现问题，按理不应出现的

等我看了日志文件，再说这个问题能否现在解决吧

**Comment by walkman205** [comment]
不好意思没更新，已经解决了。解决办法是在打开应用程序的时候就选择"以管理员身份打开",之前有问题是因为打开之后点"开始"才授权。然后就会卡住

**Comment by HSLix** [comment]
原来如此，自动获取管理员权限在2.1.7并不完善，但在2.1.8已经成功应用，可以期待后续更新

**Comment by HSLix** [comment]
2.1.8已更新，可以反馈下问题解决了吗？
