### ISSUE TITLE
无法组成完整队

### ISSUE THREAD

**Issue by walkman205** [HSLix/LixAssistantLimbusCompany#21]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

这个问题是这两天刚出现的，普通镜牢2第一次进入选人界面时，不会选择队伍，一直点击"to battle"。

如果中途进入游戏（当缩放出现问题找不到下一个路径的时候发生，概率还蛮大的），会依次点击12个人格的位置(虽然只有7个人格），然后点击"to battle”。

例如：当队伍最大人数为6时，会出现的问题是，先选择了前6个人格，然后点第七个人格(什么都不会发生），再点击之后的空位（8-12的位置）。这时候并不会直接to battle（有点儿怪）。会重新再点一遍所有人格，这样会把前六个人格取消，只选了第七个人格出战。之后这个人格大概率会死亡然后游戏又会在选人界面卡住。

看了一下log，不知道是不是每次选完人格都会检测full team的pics。可能是这个图没有能识别的问题？

### 重现问题

当重新进入镜牢，选择战斗，需要选人时会重现问题。

### 日志文件

[warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12884673/warningLog.log)
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12884700/debugLog.log)

**Comment by walkman205** [comment]
https://www.youtube.com/watch?v=Bokp3lb87yQ
这是录屏，希望有帮助

**Comment by DAtiancheng** [comment]
我也是出现了同样的问题

**Comment by halfyua** [comment]
我也有类似的问题，就不另提一个了，原本都好好的，今天突然出现，只是我是出现在经验本和纽本(影片中的人数是因为脚本中间才开始录所以才没满，不然预设人数都是5/5的)
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12887446/debugLog.log)
https://imgur.com/a/NHlnz2H

**Comment by HSLix** [comment]
> https://www.youtube.com/watch?v=Bokp3lb87yQ 这是录屏，希望有帮助

感谢反馈，图像识别正在升级中

**Comment by HSLix** [comment]
> 我也有类似的问题，就不另提一个了，原本都好好的，今天突然出现，只是我是出现在经验本和纽本(影片中的人数是因为脚本中间才开始录所以才没满，不然预设人数都是5/5的) [debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12887446/debugLog.log) https://imgur.com/a/NHlnz2H

从你的视频看 ，你的版本应该比较旧了，可以试下2.1.7看看

**Comment by halfyua** [comment]
> > 我也有类似的问题，就不另提一个了，原本都好好的，今天突然出现，只是我是出现在经验本和纽本(影片中的人数是因为脚本中间才开始录所以才没满，不然预设人数都是5/5的) [debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12887446/debugLog.log) https://imgur.com/a/NHlnz2H
> 
> 从你的视频看 ，你的版本应该比较旧了，可以试下2.1.7看看

我使用的是最新版本哦，而且好像也有其他人遇到类似状况，感觉是这次月计这次更新改了什么导致的状况，不然更新前是能正常使用的

**Comment by HSLix** [comment]
感谢进一步反馈，我下了2.1.7发现相同问题，2.1.8会在确认镜牢稳定后尽快发布



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月15日 07:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [HSLix/LixAssistantLimbusCompany] 无法组成完整队 (Issue #21) |

我也有类似的问题，就不另提一个了，原本都好好的，今天突然出现，只是我是出现在经验本和纽本(影片中的人数是因为脚本中间才开始录所以才没满，不然预设人数都是5/5的) debugLog.loghttps://imgur.com/a/NHlnz2H

从你的视频看 ，你的版本应该比较旧了，可以试下2.1.7看看

我使用的是最新版本哦，而且好像也有其他人遇到类似状况，感觉是这次月计这次更新改了什么导致的状况，不然更新前是能正常使用的

**Comment by HSLix** [comment]
2.1.8已更新，可以反馈下问题解决了吗？

**Comment by halfyua** [comment]
> 2.1.8已更新，可以反馈下问题解决了吗？

目前都能正常运行，辛苦了

**Comment by HSLix** [comment]
> > 2.1.8已更新，可以反馈下问题解决了吗？
> 
> 目前都能正常运行，辛苦了

好好好好好！！

**Comment by HSLix** [comment]
既然如此，类似的issue也关了吧，有问题再提新的issue就行啦
