### ISSUE TITLE
经验本重复选人无法战斗

### ISSUE THREAD

**Issue by GYLuuing** [HSLix/LixAssistantLimbusCompany#22]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

今天遇到的问题，多次尝试之后发现不论选没选满5个人，都会一直重复选人的步骤

### 重现问题

暂不确定

### 日志文件

[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12900635/debugLog.log)
[warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12900636/warningLog.log)

### 截图

https://www.bilibili.com/video/BV1a94y1t7qJ/

### 应该是？

选人后自动开始战斗

**Comment by HSLix** [comment]
感谢提的issue，bug已经修复，现在正在调整数值确保稳定与流畅，2.1.8新版本会尽快发布

**Comment by HSLix** [comment]
2.1.8已更新，可以反馈下问题解决了吗？

**Comment by HSLix** [comment]
根据其它人反馈，这个问题应是解决的，要是还有问题，就提新的issue吧
