### ISSUE TITLE
什么时候更新啊

### ISSUE THREAD

**Issue by wenhua200** [HSLix/LixAssistantLimbusCompany#23]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

rt
我已经三天没打开边狱了（悲）

**Comment by HSLix** [comment]
谢谢你的催更呀，开发者这边已经一百万匹磁力转动了口牙，想必新版本就快了罢（

**Comment by HSLix** [comment]
2.1.8已更新，来测吧

**Comment by ato806** [comment]
我刚刚挂了倆把镜牢2，先说优点，这个版本的识图比原来版本快了不少，十分的流畅（特别是楼层转换后的时候，以前的延迟没了），日/周奖励的领取点击快了一倍左右，自动获取管理员权限也没有问题（不用手动管理员权限运行真香），但还是有一点小瑕疵，我发现现在版本在推关中识别到往右下的路径时，是会缩放的，但似乎放大倍率小了一点，在第4/5层时，第6，7位的罪人图标会盖住路径点导致无法识别，从而退出去重进。
谢谢开发者大大，又可以快乐挂机口牙

**Comment by HSLix** [comment]
> 我刚刚挂了倆把镜牢2，先说优点，这个版本的识图比原来版本快了不少，十分的流畅（特别是楼层转换后的时候，以前的延迟没了），日/周奖励的领取点击快了一倍左右，自动获取管理员权限也没有问题（不用手动管理员权限运行真香），但还是有一点小瑕疵，我发现现在版本在推关中识别到往右下的路径时，是会缩放的，但似乎放大倍率小了一点，在第4/5层时，第6，7位的罪人图标会盖住路径点导致无法识别，从而退出去重进。 谢谢开发者大大，又可以快乐挂机口牙

右下角一般不成问题，问题在于点击问号、巴士、椅子这类非战斗节点后，即使用滚轮回复视角，也大概率会出现与正常关卡位置不同，即便如此，退出重进也比打战斗快些

解决办法也有，1、最简单也最麻烦的方法，那便是每次点完非战斗节点后，能对整个游戏窗口截图，我再多做几种事件应对，但现有的够用，我不会加的；2、采用更为高级的识图算法，我想走这条，等我学到一些再说

总之感谢你的认真测试与点评呀！！

**Comment by HSLix** [comment]
嘛，2.1.8更了，这个issue也关了罢，另外希望催更可以通过bilibili，github最好还是与开发相关些好
