### ISSUE TITLE
开发需求：重构GUI

### ISSUE THREAD

**Issue by HSLix** [HSLix/LixAssistantLimbusCompany#25]
rt，现在的tk再用下去对于以后的继续开发、维护十分不利，还是得重构一下：
现有方案：
1、使用QT
2、自行包装tk

本人倾向方案1，也欢迎有意加入开发的同学提出自己的建议和想法，或提pr

**Comment by walkman205** [comment]
[myGUI.zip](https://github.com/HSLix/LixAssistantLimbusCompany/files/13197669/myGUI.zip)
因为平时不用python，属于是边学边改。但是很想提供帮助。试着改了200行，请作者看一下进度和有没有帮助，可以的话我把剩下的也改了，有些不知道咋改的可能还需要作者自己看一下。抱拳了

**Comment by HSLix** [comment]
> [myGUI.zip](https://github.com/HSLix/LixAssistantLimbusCompany/files/13197669/myGUI.zip) 因为平时不用python，属于是边学边改。但是很想提供帮助。试着改了200行，请作者看一下进度和有没有帮助，可以的话我把剩下的也改了，有些不知道咋改的可能还需要作者自己看一下。抱拳了

首先感谢你的支持，我也十分抱歉我没能第一时间回应，因为我自己还没想好，图形化到底要做成怎么样才能方便维护与开发，所以我一直踌躇。

我看了代码，改到了使用说明界面，挺不错的，更改成的箱庭布局或许比现在的tk更好用，希望可以看到完全更改后的代码。

另外，其实我自己有试着用qt5来做，但做不成类似MAA的效果，如下图
<img width="307" alt="LALCQt界面设计" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/112762490/8a3429b1-b812-4752-85d4-abd6b053c99a">
<img width="314" alt="image" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/112762490/1c6c6a82-2c98-4788-bd9e-8ae1e8728f68">

问题出在标题栏模仿不出来，而且我也很好奇到底如何优雅简洁地实现前后端传参，还得好好学习MAA源码

当然，上面的另外不是对你说的要求，只是我自己对于GUI未来更新成品的期望，有思路的话一起探讨，慢慢实现吧，一起加油

**Comment by HSLix** [comment]
这个东西我还是自己慢慢研究吧，自己造的屎山，自己就得好好重构
