### ISSUE TITLE
doesnt work on the latest limbus version v2.1.8

### ISSUE THREAD

**Issue by Chalice12** [HSLix/LixAssistantLimbusCompany#27]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

when entering the mirror dungeon, it isnt able to progress further due to the latest limbus updates changes to the preset function

### 重现问题

set it to run mirror dungeon
notice how it always backs out after going to the preset screen

### 日志文件

i do not think these are necessary

**Comment by HSLix** [comment]
Thanks for your issue. v2.1.8 have been outdated since limbus updated yesterday.

These problems will be fixed in next version.

**Comment by HSLix** [comment]
2.1.9 has come, have a try?

**Comment by Chalice12** [comment]
it works now after replacing the enter image, thank you
