### ISSUE TITLE
希望LALC能够有一个停止重进的选项框

### ISSUE THREAD

**Issue by Lagesan** [HSLix/LixAssistantLimbusCompany#28]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

我说的“停止重进”比如说当你在打镜牢时把LALC关了，然后再打开LALC勾选重进选项框就不用再购买绿饼，直接“resume”读档，继续打本

**Comment by HSLix** [comment]
你的意思是，应该添加购买绿饼的开关是吗

**Comment by Lagesan** [comment]
对

**Comment by northtwi** [comment]
感觉没必要，镜牢打完可能升级体力就满了，而且买个绿饼也没啥费时间的

**Comment by HSLix** [comment]
选择购买绿饼的开关会加上的，毕竟也可能有保留体力的时候

**Comment by Lagesan** [comment]
好的，谢谢

**Comment by HSLix** [comment]
才发现买绿饼开关加上了
