### ISSUE TITLE
请问可以支持电脑端安卓模拟器吗？

### ISSUE THREAD

**Issue by Dermitius** [HSLix/LixAssistantLimbusCompany#29]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

很多人无法使用steam端进行游戏，希望可以有电脑端安卓模拟器适配，谢谢！

**Comment by HSLix** [comment]
感谢你对LALC的期望，不过电脑端安卓模拟器方面的项目，已经有其它开发者正在进行。

比如MAALimbusCompany，直接搜索，或者从友链里都能找到。
