### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by halfyua** [HSLix/LixAssistantLimbusCompany#3]
跑到一半突然出现 当前介面无法返回初始主介面，无法继续任务  停留的画面是镜本2 ego三选一的画面
<img width="621" alt="螢幕擷取畫面 2023-09-24 120245" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/134657090/0bef474e-ad0f-40a3-a721-43c462396c4a">
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12707758/debugLog.log)

**Comment by HSLix** [comment]
谢谢你的反馈与支持，这个情况可能是由于黑屏加载时间可能过长，触发返回机制，但返回机制仍有不足引起的。

我会在2.1.6版本修复这个问题，在此之前，请在遇到这种问题时手动选择ego暂时过渡。

**Comment by HSLix** [comment]
2.1.6版本已发布，针对这个问题做了相应优化，如果仍出现类似问题，希请给我整个流程的录屏辅助修复开发。

**Comment by halfyua** [comment]
也太有效率了吧 感谢
