### ISSUE TITLE
I don't know how to zoom to 150%

### ISSUE THREAD

**Issue by Chichans** [HSLix/LixAssistantLimbusCompany#30]
![LALC_WkntHmmzO1](https://github.com/HSLix/LixAssistantLimbusCompany/assets/149839649/df679742-34c2-48cc-ba9e-067b4fffce41)

I can't find that option anywhere, if you could tell me where it is I would appreciate it.

**Comment by HSLix** [comment]
1、Right-click on an empty space on your desktop and select "Display settings" from the context menu.
2、In the Display settings window, scroll down to find the "Scale and layout" section.
3、Here, you'll see a dropdown menu under "Change the size of text, apps, and other items". This is where you can set the zoom level. The default is usually 100%, but you can increase it to 125%, 150%, or even 175% or 200% if you prefer larger text and images.

Once you select a new zoom level, your display will automatically adjust to the new size.
