### ISSUE TITLE
无需调整系统缩放至150%的可能性

### ISSUE THREAD

**Issue by VictorVvVv** [HSLix/LixAssistantLimbusCompany#34]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

每次使用都需要调整成150%，用完再调回来，比较麻烦，以后有没有可能适配100%缩放或者自动调整？

**Comment by HSLix** [comment]
通过程序调整系统缩放对于普通的python程序不太可能，要能实现的话，应该属于黑客的范畴了

应该有两套方案
1、改进识图算法，使得可以无视一定程度的大小缩放、方向旋转识图；
这是我正在学习的方向，但感觉距离实现有些距离

2、完善图库，即在100%缩放情况下对相关图片截图，然后将不同缩放图库分开，视情况调用
这个是现在可以实现的，有意向者可以在整理好图片后提pr，到时让程序根据屏幕缩放情况选择图库就行

**Comment by VictorVvVv** [comment]
完善图库具体需要什么要求，怎么操作？

**Comment by HSLix** [comment]
> 完善图库具体需要什么要求，怎么操作？

唔，我确实忘记补充具体做法了

比如，你要做缩放100%的图库，那么就需要在缩放100%情况下，与已有的图库对应着来截图。还是挺繁琐的

另外，月计准备合并镜牢+改部分UI+镜牢三，所以图库可能会有变动

**Comment by ZengXiaoPi** [comment]
我觉得这是极好的，请务必研究出来
