### ISSUE TITLE
Does not recognize "Enter" button.

### ISSUE THREAD

**Issue by LCBUser** [HSLix/LixAssistantLimbusCompany#35]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

Hello! I've been having an issue with the program ever since today's update, I'm not sure whether that's why it stopped working. Also apologies, I do not speak chinese  ><

### 重现问题

- Launch the game normally
- Open LALC
- Set Mirror 2 Normal
- Let the script play out

### 日志文件

[2023-11-08.0001.infoLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13303808/2023-11-08.0001.infoLog.log)
[2023-11-08.0001.warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13303810/2023-11-08.0001.warningLog.log)
[2023-11-08.0001.debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13303811/2023-11-08.0001.debugLog.log)

### 截图

![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/150316788/49b35b95-db20-4f41-bafd-4239d63f3ba0)

### 应该是？

The program should hit "Enter" and keep the script running. If I press "Enter" the script keeps playing as it should, however it does not recognize "Enter" on its own. 

### 其他信息

150% Zoom, Windows 10, [V2.1.9](https://github.com/HSLix/LixAssistantLimbusCompany/releases/tag/V2.1.9), Limbus Company V.1.26.0

**Comment by HSLix** [comment]
I see. According to the log, the recognizing of "Enter" have something wrong.

You can make a screenshot of the "Enter"，name it “Enter.png”, and replace the picture "./pic/mirror/mirror2/way/Enter.png".

It seem that the algorithm has a lot to improve.
