### ISSUE TITLE
月计加入了快捷键，改用按键可以更高效自动战斗

### ISSUE THREAD

**Issue by sstareven** [HSLix/LixAssistantLimbusCompany#36]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

最新版本可以通过用P+Enter的按键输入就可以直接进行自动战斗了！消除了原来使用鼠标点击会容易第一下失灵的问题，这里稍微提一嘴。

**Comment by HSLix** [comment]
是的，而且也顺便解决了战斗减员导致winrate后无法开打的问题，以及各种之前比较头疼的返回问题。

But！周末考试，看看后面有时间才能搞搞
