### ISSUE TITLE
关于镜牢次数错误的问题，关于“无法返回到主界面的问题”的问题

### ISSUE THREAD

**Issue by GYLuuing** [HSLix/LixAssistantLimbusCompany#38]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

1.由于最近发现模块数量和通行证等级有异常，所以我特意留意了一下，通行证等级为102级，今天早上的模块数量是50，昨晚体力自回5个，购买体力两次7+6共13个，到四点多体力自回4个，LALC设置镜牢2为3+2共五次，则模块的数量应为
50+5+7+6+4-15-10=47，
通行证等级应为102+15=117
然而现在发现模块数量只有33个，通行证等级为129级，即使算上周日常的任务奖励也不会差这么多级的，所以我认为程序可能存在一些错误导致会执行超过设置的次数。
2.我发现在使用n辛打镜牢时会由于进入侵蚀状态而出现“无法返回主界面”的情况，这种情况还会随机出现在战斗过程中，选关过程中，在今天看到过两次，没看到的时候就不清楚了

### 重现问题

先设置3次镜牢，完成后不关闭程序，设置两次镜牢

### 日志文件

[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13438417/debugLog.log)
[warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13438465/warningLog.log)

**Comment by GYLuuing** [comment]
[Uploading debugLog.log…]()
[Uploading warningLog.log…]()

**Comment by HSLix** [comment]
抱歉，没能第一时间回。

这个问题从日志上上看，mirror2正常结算了5次，且从代码逻辑来看，只可能少完成（但结果也会显示正确的完成次数），不可能多完成（也可能有我未考虑但实际存在的情况），暂且先作为bug吧，也邀请看到这里的其他人一起复现，能录屏最好了

关于侵蚀状态导致无法返回，我看日志，貌似是出现在镜牢战斗刚结束，然后空循环触发返回主界面重置并返回失败的情形，可以的话请补充一下吗？当时是战斗失败了吧，但回到主界面也有处理战斗后的情况，难以想象是怎样的情况导致的
