### ISSUE TITLE
提供可被外部使用的API

### ISSUE THREAD

**Issue by MinuteSphinxE** [HSLix/LixAssistantLimbusCompany#39]
### 应该被确定的

- [X] 我确定这是一个建议，而不是遇到了问题。
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等

### 建议

可以将项目引用作为一个python库，提供简单的API，方便二次开发。

**Comment by HSLix** [comment]
十分感谢你的建议，我会努力将这个项目做成这样的 ~~（新建文件夹~~

**Comment by MinuteSphinxE** [comment]
允许提交pr吗

**Comment by HSLix** [comment]
> 允许提交pr吗

当然可以啦，而且做的时候如果有不确定的地方，欢迎在这留言讨论
