### ISSUE TITLE
出现了小问题

### ISSUE THREAD

**Issue by lmasterf** [HSLix/LixAssistantLimbusCompany#4]
卡在了这个界面
![4S}RN3QLSJEP4(((J TYO)6](https://github.com/HSLix/LixAssistantLimbusCompany/assets/142130761/69f55afc-81d0-4398-a775-65a80e05e224)
![SJ(}K7CI_~55YLD1 )YZ_%9](https://github.com/HSLix/LixAssistantLimbusCompany/assets/142130761/0fcbf7ef-f1df-4949-9bc7-3a3ddd3c5747)
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12707921/debugLog.log)

**Comment by HSLix** [comment]
我想核对几件事，1、你下的是最新的2.1.6版本吗？2、你的系统是win10或win11吗？3、你的屏幕缩放是否是150%

**Comment by HSLix** [comment]
只要把屏幕缩放调为150%，能塞下完整游戏窗口的情况都能正常识图，这是我自己测试的情况。

如果你已经调缩放到150%还不行，还请你补充一下你的屏幕分辨率，我试着复现一下

**Comment by lmasterf** [comment]
是2.1.6，win11系统，电脑分辨率是3200*2000

**Comment by HSLix** [comment]
额，我短时间搞不到3200*2000的屏幕分辨率测试

所以我想再次确认，屏幕缩放真的是150%吗？

**Comment by HSLix** [comment]
或者稍后下载2.1.7，启动后截图让我看一下日志里面检测分辨率和缩放的参数

**Comment by lmasterf** [comment]
好的，感谢感谢，大佬效率真高

**Comment by HSLix** [comment]
这样，你再试试缩放从100%到250%都试试，看看哪个缩放能识图
再不行我就弄2.1.7出来

**Comment by lmasterf** [comment]
好的，我待会去看看

**Comment by HSLix** [comment]
要是缩放怎么调也不行，请麻烦保持缩放150%情况下，把分辨率调到2560x1600，这是我的屏幕设置。如果也不行，再试试1920x1200或者1920x1080 。

我得确定问题是3200x2000的分辨率，还是其它问题

**Comment by HSLix** [comment]
2.1.7版本已发布，可以测试一下，最好可以反馈一下问题是否解决

**Comment by HSLix** [comment]
emm，一周了，如果还有问题就提新issue，这个先关了
