### ISSUE TITLE
几个问题的综合以及我的解决方案

### ISSUE THREAD

**Issue by Kanyooooo** [HSLix/LixAssistantLimbusCompany#45]
### 问题一
https://github.com/HSLix/LixAssistantLimbusCompany/issues/43
例如这里事件失败后无法进入战斗，且一直点击skip的行为，在白色棉花的事件中也有。

### 问题二
https://github.com/HSLix/LixAssistantLimbusCompany/issues/44
还有这里出现的如果有人死亡，则有概率无法正常点击攻击状态

### 问题一
应该是没有检测到可用图片方式。

### 问题二
如果把战斗检测执行的方式更改为：检测到“win rate”案件，执行“键入p”，0.1秒后“键入enter”应该就可以了。

## 我的解决方案：
如果有需要，你可以下载我自己做的辅助本脚本的辅助脚本，主要的操作是协助此脚本进行运行直到人为关闭为止。

使用和代码讲解放在bilibili
链接：https://www.bilibili.com/video/BV17b4y1L7Kf/?spm_id_from=333.999.0.0&vd_source=1e0b6a1f2db66e000aa3d6b88788e117

以下为下载地址
奶牛快传：
https://cowtransfer.com/s/3689678cbe3849 点击链接查看 [ LALC辅助脚本.zip ] ，或访问奶牛快传 cowtra删nsfer.co除m 输入传输口令 bfrg9u 查看；

百度网盘：
链接：https://pan.baidu.com/s/1MIa7BPgp9djSHhh-yF-72g?pwd=LALC 
提取码：LALC 

## 十分感谢LALC作者为解放我们的双手做出的重大贡献（哭）
我也想为了开源事业做出一份贡献（雾

**Comment by feiyingwen** [comment]
起猛了，看见了脚本的脚本

**Comment by Namu277** [comment]
why cant mine auto accept the begin now dialog box like yours in the video, I am using your script and LALC
![Uploading image_2023-12-12_162845454.png…]()

**Comment by Namu277** [comment]
![image_2023-12-12_162913358](https://github.com/HSLix/LixAssistantLimbusCompany/assets/88963133/6725dfa5-53db-4f26-ae73-dfb13bbf4698)

**Comment by Kanyooooo** [comment]
Because in the Chinese system, the [ok] button is represented by the text [确定]. 
So, OpenCV can't detect the Chinese version of the button due to differences in language text. 
You can replace [\LALC Auxiliary Script\images\ensure.png] with the English version.

The specific steps are as follows: with the screen scaled at 150%, use Win+Shift+S to take a screenshot. Refer to the original image for the exact screenshot result.

If you still have some problems. Please feel free to let me know. I will do my best to assist you.

**Comment by Namu277** [comment]
> Because in the Chinese system, the [ok] button is represented by the text [确定]. So, OpenCV can't detect the Chinese version of the button due to differences in language text. You can replace [\LALC辅助脚本\images\ensure.png] with the English version.
> 
> The specific steps are as follows: with the screen scaled at 150%, use Win+Shift+S to take a screenshot. Refer to the original image for the exact screenshot result.
> 
> If you still have some problems. Please feel free to let me know. I will do my best to assist you.

thanks it works perfectly now , amazing script btw<3

**Comment by HSLix** [comment]
总之多谢啦，要是能直接改在LALC就更好了
