### ISSUE TITLE
镜牢无法选人

### ISSUE THREAD

**Issue by sunny1654** [HSLix/LixAssistantLimbusCompany#48]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

在选择镜牢1时，卡在选人界面无法编队，疑似是新ui的问题。
<img width="68" alt="FullTeam1" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/147325048/a9d1e088-01b2-4a10-9779-750077330bf5">
zhe'ge这个照片游戏里给改没了

### 重现问题

运行脚本就会发生

### 日志文件

<img width="842" alt="屏幕截图 2023-12-07 235157" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/147325048/ed9f9f1a-29be-43cc-bc7a-3759c83430aa">

**Comment by lulufen** [comment]
我也遇到了，自己查了下代码和log，播报员Announcer重新截图替换了下就好了，不知道为啥月计改了Announcer的大小写

**Comment by sunny1654** [comment]
换了也没用，不选人就直接回主界面了
