### ISSUE TITLE
新问题求解决

### ISSUE THREAD

**Issue by zolgen** [HSLix/LixAssistantLimbusCompany#5]
之前提过的无法选人问题解决了，但是镜本刷一遍之后会重新进一遍，然后在第一关那里退出去领任务，然后就结束了，不会再刷

**Comment by HSLix** [comment]
发下日志文件吧，我自己测试没有复现这样的情况

**Comment by zolgen** [comment]
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12710250/debugLog.log)

**Comment by zolgen** [comment]
好的大佬，日志文件已经上传，昨晚忘了这回事

**Comment by zolgen** [comment]
> 发下日志文件吧，我自己测试没有复现这样的情况
好的大佬，日志文件已经上传，昨晚忘了这回事

**Comment by HSLix** [comment]
我自己又测试几遍，没有你说的情况。

检查了日志，如果你没有手动干预运作的话，程序确实没有识别到镜牢结算部分。

可以的话，试着打一次镜牢2，看看结算部分是否正常。以此判断是不是镜牢1和2的图片素材有问题

另外，发日志时，可以的话，标一下异常部分是哪段时间，以及有warningLog也可以一起发

**Comment by zolgen** [comment]
好的大佬，谢谢大佬解答，我这个号刚解锁镜2今天试一试

**Comment by danny04255** [comment]
大老我這裏出了一個 cp932 codec cant cant encode character \u9879 想請問該怎麼解決

**Comment by zolgen** [comment]
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12715714/debugLog.log)
[warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12715715/warningLog.log)

**Comment by HSLix** [comment]
> 大老我這裏出了一個 cp932 codec cant cant encode character \u9879 想請問該怎麼解決

如果遇到与该issue无关的问题，提出新的issue会比较好。

这个报错的意思是，程序中出现cp932字符集中没有的字符，cp932根据
https://blog.csdn.net/dietime1943/article/details/60577428
这篇文章，貌似是日文的标准字符集，你看一下你本地的一些字符配置要怎么改成用utf-8来打开

这个问题我会在下次的2.1.7版本更新中解决，可以等待下次更新再测试

**Comment by zolgen** [comment]
> 我自己又测试几遍，没有你说的情况。
> 
> 检查了日志，如果你没有手动干预运作的话，程序确实没有识别到镜牢结算部分。
> 
> 可以的话，试着打一次镜牢2，看看结算部分是否正常。以此判断是不是镜牢1和2的图片素材有问题
> 
> 另外，发日志时，可以的话，标一下异常部分是哪段时间，以及有warningLog也可以一起发

大佬，镜二我测试过了，主要过程就是在第一次镜本打完后，他会回到主页面换体力然后再回到镜本，然后在这里点击一次“preset”（延用上次队伍配置）后回到主界面再次清体力，然后回到镜本。接下来就正常选人进入第一层地图，然后回主页面清体力进入通行证邮箱拿奖励，最后就显示结束任务

**Comment by zolgen** [comment]
[Uploading debugLog.log…]()
[warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12718295/warningLog.log)

**Comment by zolgen** [comment]
[warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12718302/warningLog.log)

**Comment by zolgen** [comment]
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12718304/debugLog.log)

**Comment by zolgen** [comment]
大概是在26日2:12:04那里开始发生异常，就是第一次镜本通关开始刷第二次的时候，进入选人页面会突然退出去
然后就是第三次进入镜本，在第一层地图退出就结束任务那里，不过我无法确定这个在哪个时间段发生，大概是在2:14左右

**Comment by HSLix** [comment]
经过日志检查和你的反馈，我判断问题是第二次选人中，点击preset后的等待时间过短，且领取奖励后有一些卡顿处导致程序有流程反复执行。所以程序判断循环次数过多异常。

总之，我把相关程序的等待时间和流程做了优化，届时可以下载2.1.7版本再测试。

最好你可以把你的一次镜本结算到第二次镜本选人又退出的地方录屏下来，我对中间卡顿的地方和情况很感兴趣，或许还能更好地解决这种问题。

**Comment by zolgen** [comment]
好的，我会在今天进行录屏然后上传，感谢大佬帮忙

**Comment by zolgen** [comment]
Uploading QQ视频20230926091559.mp4…

**Comment by zolgen** [comment]
链接：https://pan.baidu.com/s/15KhYNMOQAphGUNwOsCAPCw 
提取码：1234

**Comment by zolgen** [comment]
大佬，由于视频体积超过10mb无法直接上传到这里，我把它发在了百度网盘，大小大约有40m，不知道你方不方便看。如果可以的话能否私信我联系方式呢，如果你不方便使用百度网盘我也可以通过联系方式把视频发送给你，具体的解答方案我也会发在评论区让其他遇到和我相似问题的人看到

**Comment by HSLix** [comment]
我看到了，也辛苦你拍这个视频了，我会对相关函数做进一步优化，请下载稍后的2.1.7做进一步测试吧

> 大佬，由于视频体积超过10mb无法直接上传到这里，我把它发在了百度网盘，大小大约有40m，不知道你方不方便看。如果可以的话能否私信我联系方式呢，如果你不方便使用百度网盘我也可以通过联系方式把视频发送给你，具体的解答方案我也会发在评论区让其他遇到和我相似问题的人看到

**Comment by zolgen** [comment]
好的，感谢大佬更新

**Comment by HSLix** [comment]
> 大老我這裏出了一個 cp932 codec cant cant encode character \u9879 想請問該怎麼解決



> 好的，感谢大佬更新

2.1.7版本已发布，可以测试一下，最好可以反馈一下问题是否解决

**Comment by zolgen** [comment]
感谢大佬，问题已经解决，新版本软硬适中酸甜解腻，老人孩子都很爱吃

**Comment by HSLix** [comment]
> 感谢大佬，问题已经解决，新版本软硬适中酸甜解腻，老人孩子都很爱吃

谢谢你的肯定啦，就是表述过于形象，搞得我现在有点饿
