### ISSUE TITLE
湖镜适配

### ISSUE THREAD

**Issue by ZengXiaoPi** [HSLix/LixAssistantLimbusCompany#50]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

RT

**Comment by Kanyooooo** [comment]
催更

**Comment by terlans** [comment]
催更+1

**Comment by ImYiFeng** [comment]
催更

**Comment by HSLix** [comment]
也许快了，应该能赶2023结束前更一下，maybe possible……

**Comment by ZengXiaoPi** [comment]
> 也许快了，应该能赶2023结束前更一下，maybe possible……

看起来会是个大工程。
另外会支持更换队伍吗？例如从沉沦切呼吸法再切充能之类的，还是只能单队刷

**Comment by HSLix** [comment]
> 看起来会是个大工程。
> 另外会支持更换队伍吗？例如从沉沦切呼吸法再切充能之类的，还是只能单队刷

这一版能动就行，先解决温饱，再解决吃好

切换队伍会搞但不优先，换队伍加成还没那么大
