### ISSUE TITLE
在新开副本确定总体队伍时无法继续进行

### ISSUE THREAD

**Issue by Ravens118** [HSLix/LixAssistantLimbusCompany#52]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

在脚本打开新的副本确定12个人时，会点击李箱进入李箱人格页，然后等待一会后执行退出至主界面并循环此问题，推测是把开局12人选人的界面识别成战斗前6人的选人界面

### 重现问题

启动脚本

### 日志文件

[2023-12-29.0001.debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13790126/2023-12-29.0001.debugLog.log)
[2023-12-29.0001.infoLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13790128/2023-12-29.0001.infoLog.log)
[2023-12-29.0001.warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13790129/2023-12-29.0001.warningLog.log)

### 截图

![screenshot](https://github.com/HSLix/LixAssistantLimbusCompany/assets/150468284/59e65a03-5c9f-4876-92d7-044fa47d708e)

**Comment by HSLix** [comment]
是否下载的是我昨天更新的最新版？

**Comment by Ravens118** [comment]
> 是否下载的是我昨天更新的最新版？

是的

**Comment by Ravens118** [comment]
> 是否下载的是我昨天更新的最新版？

如果我推测的没有错，可以尝试把战斗前的识别标识由播报员修改成右下角的/6

**Comment by Ravens118** [comment]
> > 是否下载的是我昨天更新的最新版？
> 
> 如果我推测的没有错，可以尝试把战斗前的识别标识由播报员修改成右下角的/6

![6](https://github.com/HSLix/LixAssistantLimbusCompany/assets/150468284/8603a86f-f9e3-491b-9a72-8cda0aa69151)
我自己试了一下不行，可能是识别区域限制识别不到那

**Comment by HSLix** [comment]
我昨晚明明修了这个bug，不应该啊，等中午我看看刷的情况

**Comment by Ravens118** [comment]
> 我昨晚明明修了这个bug，不应该啊，等中午我看看刷的情况

欸？昨晚有更新么？网页上显示更新是两天前

**Comment by HSLix** [comment]
<img width="890" alt="image" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/112762490/5c6b607d-a390-4488-82c2-bd3317d73adf">

经测试，没有问题，你下载应该的是我前天的版本，反馈bug前请仔细看好是否有更新

**Comment by Ravens118** [comment]
> <img alt="image" width="890" src="https://private-user-images.githubusercontent.com/112762490/293307115-5c6b607d-a390-4488-82c2-bd3317d73adf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4MzY3MDYsIm5iZiI6MTcwMzgzNjQwNiwicGF0aCI6Ii8xMTI3NjI0OTAvMjkzMzA3MTE1LTVjNmI2MDdkLWEzOTAtNDQ4OC04MmMyLWJkMzMxN2Q3M2FkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQwNzUzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmI5OGI0MTYxY2I3NDM1Y2JmMjY2YzQ3MDM3MGJiYzdkNDc0MjJkY2U0NmVkZWUwNzNlZmUzMTVhMDUzNmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vnU4S2uEY4XNXFcDa3wCJiTsBihuhIQ7TEiPrJB5DXM">
> 经测试，没有问题，你下载应该的是我前天的版本，反馈bug前请仔细看好是否有更新

好嘞，点击去下载界面才看到有更新，你简直是我的超人！
