### ISSUE TITLE
湖鏡讀不到下一個節點

### ISSUE THREAD

**Issue by Louisskenn** [HSLix/LixAssistantLimbusCompany#55]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

如題，看了兩次應該是下個節點的圖標可能不存在於資料庫內，導致鼠標從來沒有點過圖片上的異想體格子？

### 重现问题

可能是剛好走到最下路線，且接下來路線向上為異想體戰時無法讀取？

### 日志文件

[2023-12-29.0001.debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13791304/2023-12-29.0001.debugLog.log)
[2023-12-29.0001.warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13791305/2023-12-29.0001.warningLog.log)

### 截图

![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/146411651/763fef47-95b4-4107-abf4-3cca10891596)

### 其他信息

按照建議為150分辨率跟最新版本

**Comment by HSLix** [comment]
补丁已打，可在release重新下载，待广泛测试

**Comment by sstareven** [comment]
> 补丁已打，可在release重新下载，待广泛测试

经测试，150%分辨率底下，打了10轮镜牢3也依然在自己跑，所以这个可以Closed了。

**Comment by Louisskenn** [comment]
掛了幾次後遇到同樣狀況，一樣也是在三層時發生，使用的是最新deug版
![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/146411651/93d12e4f-ba74-4629-b190-51710af5e175)
[2024-01-02.0001.debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13806356/2024-01-02.0001.debugLog.log)
[2024-01-02.0001.warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13806357/2024-01-02.0001.warningLog.log)

**Comment by Ravens118** [comment]
> 掛了幾次後遇到同樣狀況，一樣也是在三層時發生，會點擊左邊兩個節點但不點擊異想體戰，使用的是最新deug版 ![image](https://private-user-images.githubusercontent.com/146411651/293611959-93d12e4f-ba74-4629-b190-51710af5e175.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MTg4MjEsIm5iZiI6MTcwNDQxODUyMSwicGF0aCI6Ii8xNDY0MTE2NTEvMjkzNjExOTU5LTkzZDEyZTRmLWJhNzQtNDYyOS1iMTkwLTUxNzEwYWY1ZTE3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwMTM1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjE4MWEzZGRhNzk2ZWI3ZTk2ZjA1YzA2NDk5YWNjMzc5ZTI4ZjJhMjBmZTkwZTJlNDY3YmNlYzA5NTk2YjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sNsV_ktkl9fvOh0kPfwFNig240y4-fqzozdhHZrqxG8) [2024-01-02.0001.debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13806356/2024-01-02.0001.debugLog.log) [2024-01-02.0001.warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/13806357/2024-01-02.0001.warningLog.log)

我自己遇到后重新截取了图片替换路径LixAssistantLimbusCompany\pic\mirror\mirror3\way\Encounter里的EncounterRH，可以识别
<img width="43" alt="EncounterRH" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/150468284/9ee3b55e-709b-41f8-8b19-314f2161ac90">

**Comment by HSLix** [comment]
> > 掛了幾次後遇到同樣狀況，一樣也是在三層時發生，會點擊左邊兩個節點但不點擊異想體戰，使用的是最新deug版 
> 
> 我自己遇到后重新截取了图片替换路径LixAssistantLimbusCompany\pic\mirror\mirror3\way\Encounter里的EncounterRH，可以识别 

正解，不过我这边把小饼干刷完都没卡住，看来分辨率的不同仍对识图有一定影响
