### ISSUE TITLE
希望可以添加镜牢刷开局ego饰品的功能

### ISSUE THREAD

**Issue by ID-BLUEBERRY** [HSLix/LixAssistantLimbusCompany#56]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

并不需要全ego适配，可以仅适配类似血雾，月之记忆一类高稀有度以及高需求度的饰品

**Comment by Nishino33** [comment]
附议。因为现在血雾队真挺猛的，开局刷铁子网和袋子，到第二层椅子处换个血雾，再实现拖拽重定位的功能，就能从头杀到尾。

**Comment by Louisskenn** [comment]
跑了很多場發現對上狐貍跟銅牛基本上必輸無疑，鏡牢過程會跳出去刷新隊伍導致自動重選上面六個，幹不贏銅牛15-20或清不完狐狸的傘。

請問你們也一樣嗎？

1/11更新後基本上只要能刷血霧二層能走椅子合出，隊伍前六個已經可以完整湊出全流血亂A了。

**Comment by Nishino33** [comment]
> 跑了很多場發現對上狐貍跟銅牛基本上必輸無疑，鏡牢過程會跳出去刷新隊伍導致自動重選上面六個，幹不贏銅牛15-20或清不完狐狸的傘。
> 
> 請問你們也一樣嗎？
> 
> 1/11更新後基本上只要能刷血霧二層能走椅子合出，隊伍前六個已經可以完整湊出全流血亂A了。

是的，不光是牛和狐狸，第三层螃蟹也有很大概率翻车
