### ISSUE TITLE
問題求解決

### ISSUE THREAD

**Issue by danny04255** [HSLix/LixAssistantLimbusCompany#6]
我剛剛載了新的2.7版但是用了卻是會有胡亂點擊的狀況,呒有辦法正常使用,螢幕分辨率是2560X1440 縮放150 鼠標會一直在重複三個點跑沒有 # #

**Comment by HSLix** [comment]
另外，你之前有下过之前的版本吗？是的话，也会出现一样的情况吗？

**Comment by HSLix** [comment]
2.1.8已更新，可以反馈下问题解决了吗？
