### ISSUE TITLE
更新后镜牢3开局异常

### ISSUE THREAD

**Issue by elerspay** [HSLix/LixAssistantLimbusCompany#65]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

更新后镜牢3普通开始后有了临时星光增益界面，导致程序报错

### 重现问题

手动完成镜牢三困难，后点开镜牢三

### 日志文件

[warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/14135822/warningLog.log)
debuglog文件过大上传失败

### 截图

![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/87074575/98282049-4bb0-4a4e-9f67-28c8fc8defa1)

**Comment by HSLix** [comment]
哦哦，这个很快就会修复。另外你上传的日志是很久版本LALC的了，上传日志时，请选择有日期的日志文件哦~
