### ISSUE TITLE
征集图片以适配肉斩骨断活动镜子地牢/Collecting Pictures to fit Yield My Flesh to Claim Their Bones activity mirror dungeons

### ISSUE THREAD

**Issue by Parrthu** [HSLix/LixAssistantLimbusCompany#66]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

###这是转载的官方征集文章/This is a **OFFICAL HELP-WANTING**
为加速活动图标适配，现征集关卡图片，有意者可参考LixAssistantLimbusCompany\pic\mirror\mirror3\way中文件夹内图片格式来对活动关卡截图。
In order to speed up the adaptation of the activity's icon, we are now collecting the level picture. Example pics are in the folder LixAssistantLimbusCompany\pic\mirror\mirror3\way
要截图的关卡有，活动问号事件，活动普通战斗，活动困难战斗，活动Boss
Screenshots we need are : activity question mark event, activity ordinary combat, activity difficult combat, activity Boss
此外，Limbus的窗口应通过LALC调整过并在150%的缩放下，在火车图标正中间时截图。可通过返回主界面再次进入镜牢确保火车头在界面正中间。截图区域尽量在包含关卡中间图标的同时，没有截取到镜牢背景，人格栏或其它可能会变化的因素
In addition, the Limbus window should be pre-adjusted by LALC and resized at 150% , with a screenshot taken in the middle of the train icon. You can return to the main interface and re-enter the mirror to ensure that the locomotive is in the middle of the interface. As far as possible, the screenshot area should contains the middle of the level icon without capturing the background of the mirror, the identity bar or any other factors that may change.
命名格式：左上角图片命名LH.png，正左LM.png，左下LL.png，右上RH.png，正右RM.png，右下RL.png
Naming format: the top-left image is named LH. PNG, right left LM. PNG, lower left, LL. PNG, top right RH. PNG, right RM. PNG, lower right RL. PNG
联系方式，请发送到邮箱 [l0123i456@163.com](mailto:l0123i456@163.com) 或其它方式，可备注bilibili用户名
Please send pics and your contact information to email l0123i456@163.Com.
请将这些四组图片分别放在四个文件夹提交，一次提交一组也好，一收到通过测试的图片组就会在本动态更新进度，下次更新的备注中也会有贡献者的名字

### （原文）建议
如题，因为battle的图片改了所以需要更新一下图像。
而且感觉逻辑稍微优化一下了还可以直接刷活动地牢。感谢大佬一直以来的付出

**Comment by Lagesan** [comment]
+1

**Comment by walkman205** [comment]
其实可能只需要更改图片，要不大伙一起帮忙把需要的图片上传一下看看缺啥整一份出来。

**Comment by Parrthu** [comment]
> 其实可能只需要更改图片，要不大伙一起帮忙把需要的图片上传一下看看缺啥整一份出来。

我看到了作者在哔哩哔哩上发的动态了，我转载如下：
为加速活动图标适配，现征集关卡图片，有意者可参考LixAssistantLimbusCompany\pic\mirror\mirror3\way中文件夹内图片格式来对活动关卡截图。
In order to speed up the adaptation of the activity's icon, we are now collecting the level picture. Example  pics are in the folder LixAssistantLimbusCompany\pic\mirror\mirror3\way
要截图的关卡有，活动问号事件，活动普通战斗，活动困难战斗，活动Boss
Screenshots we need are : activity question mark event, activity ordinary combat, activity difficult combat, activity Boss
此外，Limbus的窗口应通过LALC调整过并在150%的缩放下，在火车图标正中间时截图。可通过返回主界面再次进入镜牢确保火车头在界面正中间。截图区域尽量在包含关卡中间图标的同时，没有截取到镜牢背景，人格栏或其它可能会变化的因素
In addition, the Limbus window should be pre-adjusted by LALC and resized at 150% , with a screenshot taken in the middle of the train icon. You can return to the main interface and re-enter the mirror to ensure that the locomotive is in the middle of the interface. As far as possible, the screenshot area should contains the middle of the level icon without capturing the background of the mirror, the identity bar or any other factors that may change.
命名格式：左上角图片命名LH.png，正左LM.png，左下LL.png，右上RH.png，正右RM.png，右下RL.png
Naming format: the top-left image is named **LH. PNG**, right left **LM. PNG**, lower left, **LL. PNG**, top right **RH. PNG**, right **RM. PNG**, lower right **RL. PNG**
联系方式，请发送到邮箱 l0123i456@163.com 或其它方式，可备注bilibili用户名
Please send pics and your contact information to email l0123i456@163. Com. 
请将这些四组图片分别放在四个文件夹提交，一次提交一组也好，一收到通过测试的图片组就会在本动态更新进度，下次更新的备注中也会有贡献者的名字

**Comment by HSLix** [comment]
额，抱歉现在才看到，这几天搞其他没看github

也十分感谢搬运，总之大意如上，V2.1.11在搞了，为了能高效运行正在添加“神秘功能”，现在时间安排也比较紧，故发布图片征集以加速开发

**Comment by HSLix** [comment]
感谢大家的热心支持，图片征集顺利完成，同时神秘功能开发完成，进入测试阶段，或许本周末即可发布最新版本
