### ISSUE TITLE
You are not able to edit sinner_order due to lack of permisions

### ISSUE THREAD

**Issue by lukatin9** [HSLix/LixAssistantLimbusCompany#69]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我使用的程序版本已为最新版

### 问题描述

When trying to edit the sinner_order.txt file, you receive a popup that says "You do not have permission to edit this file, please contact the owner for permission."

尝试编辑 sinner_order.txt 文件时，您会收到一个弹出窗口，显示“您无权编辑此文件，请联系所有者以获得许可。”

### 重现问题

Try to edit the file 

尝试编辑文件

### 日志文件

.

**Comment by HSLix** [comment]
I don't know either. So I google and find https://answers.microsoft.com/en-us/windows/forum/all/you-dont-have-permission-to-open-this-file-contact/af3387f2-123c-40f0-bf32-493a2554cc4d

**Comment by HSLix** [comment]
well，I just edit something on it, and ask another to try and it works.

**Comment by lukatin9** [comment]
> I don't know either. So I google and find https://answers.microsoft.com/en-us/windows/forum/all/you-dont-have-permission-to-open-this-file-contact/af3387f2-123c-40f0-bf32-493a2554cc4d

Now it works after using the metod in the link
