### ISSUE TITLE
Increase the delay before checking for poise gifts on start

### ISSUE THREAD

**Issue by lukatin9** [HSLix/LixAssistantLimbusCompany#74]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

Most of the time when the script goes to the starting gift selection it clicks on the word "poise" too quickly and the gifts on the right side of the screen don't appear and it leaves the dungeon to reroll the gifts because it doesn't detect the Neblizer, even when its present. Increasing the delay by 0.5-1 seconds should fix this issue. It's not gamebreaking but hurts the efficiency a bit.

大多数情况下，当脚本进入起始礼物选择时，它会过快地点击“平衡”一词，并且屏幕右侧的礼物不会出现，并且会离开地牢重新滚动礼物，因为它没有出现 即使雾化器存在，也不要检测到它。 将延迟增加 0.5-1 秒应该可以解决此问题。 这不会破坏游戏，但会有点影响效率。

**Comment by HSLix** [comment]
alpha2 delay 1s more in this, have a try?
