### ISSUE TITLE
风暴之镜本更新

### ISSUE THREAD

**Issue by Lagesan** [HSLix/LixAssistantLimbusCompany#79]
### 应该被确定的

- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等
- [X] 我确定这是一个建议，而不是遇到了问题。

### 建议

镜本更新了

**Comment by Lagesan** [comment]
催更

**Comment by Lagesan** [comment]
没有，我用125%也正常使用

**Comment by kenny8157235** [comment]
有發生過進入鏡牢後沒有戰鬥的問題嗎?不確定他是怎麼選角色出戰，或許需要自己設定?

**Comment by Lagesan** [comment]
没有,我这里即使没有选定角色它自己也会帮我选定
