### ISSUE TITLE
一点小问题

### ISSUE THREAD

**Issue by halfyua** [HSLix/LixAssistantLimbusCompany#8]
升级时会卡在升级画面出不去
[debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/12775685/debugLog.log)

**Comment by HSLix** [comment]
对于升级画面我是有做处理的，在我自己的电脑上不会卡住，请遵照参考格式说一下时间并提供画面，否则我很难判断

**Comment by HSLix** [comment]
2.1.8已更新，可以反馈下问题解决了吗？

**Comment by HSLix** [comment]
嘛，就当解决了吧
