### ISSUE TITLE
选卡包时卡着， 鼠标在旁边拉着罢了

### ISSUE THREAD

**Issue by jslee69** [HSLix/LixAssistantLimbusCompany#84]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题 | I have google it and can hardly find any solution.
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等 | The title is clear rather than "A advice".
- [X] 我已确认目前没有类似 issue | I have confirmed that there is no similar issue at this time.
- [X] 我使用的程序版本已为最新版 | The programme is the latest version.
- [X] 我已完整查看过项目 README，尤其是常见问题部分 | I have reviewed the project README in its entirety, especially the FAQ section
- [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 | I understand and am willing to follow up on this issue, assist with testing and provide feedback.
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 | I understand and agree with the above, and understand that project maintainers have limited energy, and that issues that don't follow the rules may be ignored or simply shut down

### 问题描述

选卡包时鼠标没有去拉卡包， 反而很像是在拉旁边的箭头罢了， 已经下载最新版本了然后重新试过还是一样问题

### 重现问题

游戏打到每一层的最后一关后就会出这个问题

### 日志文件

[2024-05-12.0001.debugLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/15284063/2024-05-12.0001.debugLog.log)
[2024-05-12.0001.infoLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/15284064/2024-05-12.0001.infoLog.log)
[2024-05-12.0001.warningLog.log](https://github.com/HSLix/LixAssistantLimbusCompany/files/15284065/2024-05-12.0001.warningLog.log)

### 视频/截图

![Screenshot 2024-05-12 030703](https://github.com/HSLix/LixAssistantLimbusCompany/assets/169554610/d2a271e8-e28a-432c-bfb2-d602f9629228)

### 应该是？

选一个卡包拉下来然后接着去下一层

### 其他信息

Windows 11
English
1920 x 1080

**Comment by gretino** [comment]
同样的问题，不过我这不止最后一层，基本上随机遇到。
win11 英文 2560x1440

**Comment by HSLix** [comment]
上传了补丁版，试试？

**Comment by gretino** [comment]
> 上传了补丁版，试试？

没看到有更新

**Comment by sinofewer** [comment]
> 上传了补丁版，试试？

补丁版本还是会一直扒拉最左侧卡包的左侧空气，或许选中间会更必中一点？毕竟歪了也会歪到旁边两个包去。

**Comment by HSLix** [comment]
> > 上传了补丁版，试试？
> 
> 我发现问题所在了，需要点开起步左边的那个主题包+1的星光，可能一部分人跟我一样感觉那个太没用就先去点别的了，4个包就是稳稳选左手第一个了

原来如此，我在初期试验时顺手就点了，导致坐标部分不合，那么问题就暂且算解决吧，感谢支持与反馈

**Comment by HSLix** [comment]
又传了个补丁包，本地测试3、4、5主题包都可以过，如果这个问题解决的话，就请关闭该issue吧。如果可以点个star支持一下就更好了：）
