### ISSUE TITLE
开局选择ego饰品卡住了。QAQ

### ISSUE THREAD

**Issue by LALC-zuozhe-nb** [HSLix/LixAssistantLimbusCompany#86]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题 | I have google it and can hardly find any solution.
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等 | The title is clear rather than "A advice".
- [X] 我已确认目前没有类似 issue | I have confirmed that there is no similar issue at this time.
- [X] 我使用的程序版本已为最新版 | The programme is the latest version.
- [X] 我已完整查看过项目 README，尤其是常见问题部分 | I have reviewed the project README in its entirety, especially the FAQ section
- [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 | I understand and am willing to follow up on this issue, assist with testing and provide feedback.
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 | I understand and agree with the above, and understand that project maintainers have limited energy, and that issues that don't follow the rules may be ignored or simply shut down

### 问题描述

6月3日，win11系统 ，100%缩放率和150%缩放率都试过。问题是：开局选择ego饰品界面，不会选择，会卡住然后退到主界面，最后报错。（在卡住的时候手动选择ego饰品后续就会正常运行，直到下一次镜牢进入开局ego饰品界面。）（尝试过重新下载，没有改善）。

### 重现问题

点击start开始，后续进入开局ego饰品选择界面。

### 日志文件

[2024-06-03.0001.debugLog.log](https://github.com/user-attachments/files/15533936/2024-06-03.0001.debugLog.log)

[2024-06-03.0001.infoLog.log](https://github.com/user-attachments/files/15533937/2024-06-03.0001.infoLog.log)

[2024-06-03.0001.warningLog.log](https://github.com/user-attachments/files/15533938/2024-06-03.0001.warningLog.log)

### 视频/截图

<img width="664" alt="Snipaste_2024-06-03_20-29-18" src="https://github.com/HSLix/LixAssistantLimbusCompany/assets/148685050/95b2045f-e51c-4e1b-a2f0-9fbfd5ea95cd">

### 应该是？

像前面的版本一样，选择一个开局饰品（随便啥都行）。

### 其他信息

操作系统：win11
语言：英语 （安装了都市零协的汉化报）
limbus版本：1.48.0
屏幕分辨率：100%，150%
软件版本：2.1.12

**Comment by HSLix** [comment]
这个问题是由于当前lalc在开局只会选随机饰品，在添加饰品倾向选项前，建议把开局饰品选择的星光关掉几个，让随机饰品能出现在界面中即可正常运行

**Comment by LALC-zuozhe-nb** [comment]
解决了，感谢作者
