### ISSUE TITLE
Random EGO gift not being selected after unlocking Wish of Stars

### ISSUE THREAD

**Issue by Hcopson** [HSLix/LixAssistantLimbusCompany#88]
### 应该确定的

- [X] 已尝试使用搜索引擎，且不能解决我的问题 | I have google it and can hardly find any solution.
- [X] 我填写的标题意义明确，而不是“一个建议”、“卡住了”等 | The title is clear rather than "A advice".
- [X] 我已确认目前没有类似 issue | I have confirmed that there is no similar issue at this time.
- [X] 我使用的程序版本已为最新版 | The programme is the latest version.
- [X] 我已完整查看过项目 README，尤其是常见问题部分 | I have reviewed the project README in its entirety, especially the FAQ section
- [X] 我理解并愿意跟进此 issue，协助测试和提供反馈 | I understand and am willing to follow up on this issue, assist with testing and provide feedback.
- [X] 我理解并认可上述内容，并理解项目维护者精力有限，不遵循规则的 issue 可能会被无视或直接关闭 | I understand and agree with the above, and understand that project maintainers have limited energy, and that issues that don't follow the rules may be ignored or simply shut down

### 问题描述

It is not clicking Random ego gifts, I think this is happening after I unlocked Wish of Stars 

### 重现问题

https://github.com/HSLix/LixAssistantLimbusCompany/assets/55904198/e374dae2-eeb3-40d3-b443-63d27d6fdaad

It used to run fine before I unlocked Wish of Stars, now it is not selecting the Random EGO

### 日志文件

[2024-06-29.0001.debugLog.log](https://github.com/user-attachments/files/16041905/2024-06-29.0001.debugLog.log)
[2024-06-29.0001.infoLog.log](https://github.com/user-attachments/files/16041906/2024-06-29.0001.infoLog.log)
[2024-06-29.0001.warningLog.log](https://github.com/user-attachments/files/16041907/2024-06-29.0001.warningLog.log)

### 其他信息

Windows 10
English
2.1.12
1920x1080 150%

**Comment by HSLix** [comment]
It's probably the first time to select the random gift. The starlight on the right side of the name makes lalc confused.

You can select it with your mouse for this time, and lalc will make it all right everytime after that.maybe:)

This bug will be fixed soon.Thanks for your issue.   :)

**Comment by Hcopson** [comment]
Thank you for your fast response and your hard work!
