### ISSUE TITLE
程序打不开

### ISSUE THREAD

**Issue by freezew101** [HSLix/LixAssistantLimbusCompany#9]
尝试打开的时候会跳这个错误，不知道是啥问题:

![image](https://github.com/HSLix/LixAssistantLimbusCompany/assets/71756764/b8dd2f3b-dabd-44ab-b973-dc75470ecc32)

**Comment by HSLix** [comment]
你很可能下载了2.1.0版吧，那一版才会报这个错误

**Comment by HSLix** [comment]
请按照以下步骤试着操作一下：
在Windows操作系统中：

打开控制面板(Control Panel)。
选择"时钟和区域"（Clock and Region）。
在"区域"（Region）部分，点击"更改日期、时间或区域格式"（Change date, time, or number formats）。
在弹出的窗口中，选择"管理"（Administrative）选项卡。
在"语言设置更改"（Language for non-Unicode programs）部分，点击"更改系统区域设置"（Change system locale）。
选择"使用Unicode UTF-8 提供全球语言支持"（Use Unicode UTF-8 for worldwide language support）。
点击"确定"（OK）按钮，并按照系统提示重新启动电脑。

**Comment by HSLix** [comment]
2.1.8已更新，可以反馈下问题解决了吗？

**Comment by Elysdfipoi** [comment]
雖然我不是原發問者，但也碰到這個問題。

照這個步驟確實解決並成功執行了：

> 请按照以下步骤试着操作一下： 在Windows操作系统中：
> 
> 打开控制面板(Control Panel)。 选择"时钟和区域"（Clock and Region）。 在"区域"（Region）部分，点击"更改日期、时间或区域格式"（Change date, time, or number formats）。 在弹出的窗口中，选择"管理"（Administrative）选项卡。 在"语言设置更改"（Language for non-Unicode programs）部分，点击"更改系统区域设置"（Change system locale）。 选择"使用Unicode UTF-8 提供全球语言支持"（Use Unicode UTF-8 for worldwide language support）。 点击"确定"（OK）按钮，并按照系统提示重新启动电脑。

**Comment by HSLix** [comment]
唔，这个问题感觉看到好几次了，要是编个Q&A一定得把这个写进去
